[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = [
  "corepack disable",
  "npm install -g yarn@4.9.2",
  "yarn install --frozen-lockfile --network-timeout 600000"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn vite preview --host 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production"
YARN_CACHE_FOLDER = "/tmp/.yarn-cache"
COREPACK_ENABLE_STRICT = "0"