# Nixpacks Fallback Configuration for Z2 Platform
# This serves as backup configuration if Railpack fails

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@4.9.2 --activate",
  "yarn set version 4.9.2",
  "yarn install --immutable"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn vite preview --host 0.0.0.0 --port $PORT"