checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

enableScripts: true

enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

# Use hardlinks for faster installs (Railway optimization)
nmMode: hardlinks-local
