compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

nodeLinker: node-modules

# Prevent conflicting package managers and ensure consistency
enableScripts: true

# Optimize performance for workspaces
nmHoistingLimits: workspaces

# Allow lockfile modifications in development
enableImmutableInstalls: false
