# Railway.app Configuration for Z2 Platform

services:
  # Backend API Service
  backend:
    source: backend
    build:
      buildCommand: poetry install --no-dev
      watchPaths:
        - backend/app/**
    deploy:
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
      healthcheckPath: /health
      restartPolicyType: on_failure
    variables:
      PYTHON_VERSION: 3.11
      POETRY_VERSION: 1.6.1
    domains:
      - z2-api.railway.app
    
  # Frontend Web App
  frontend:
    source: frontend
    build:
      buildCommand: npm ci && npm run build
      publishPath: dist
      watchPaths:
        - frontend/src/**
    deploy:
      staticSite: true
    domains:
      - z2.railway.app

  # PostgreSQL Database
  postgres:
    image: postgres:15
    variables:
      POSTGRES_DB: z2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{Postgres.POSTGRES_PASSWORD}}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

# Environment variable templates
environments:
  production:
    variables:
      # Backend
      DEBUG: false
      LOG_LEVEL: INFO
      DATABASE_URL: ${{Postgres.DATABASE_URL}}
      REDIS_URL: ${{Redis.REDIS_URL}}
      
      # Frontend
      VITE_API_BASE_URL: https://z2-api.railway.app
      VITE_ENABLE_DEBUG: false