providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "gcc", "postgresql_16"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install poetry==1.8.5",
  "poetry config virtualenvs.create false",
  "poetry install --no-root --only=main"
]

[start]
cmd = "poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2 --threads 4"

[variables]
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
PORT = "8000"